#!/bin/bash

#echo "new directory: $DIR"
for run in {1..100} #number of generations
do
	for runIn in {1..5} #number of chromosomes
	do
		echo "run number: $runIn"
	 	ant competeLadder &
	 	sleep 1  # Waits 1 second
	 	ant competeLadder &
	 	sleep 1  # Waits 1 second
	 	ant competeLadder &
	 	sleep 1  # Waits 1 second
	 	ant competeLadder &
	 	sleep 1  # Waits 1 second
	 	ant competeLadder 
	 	sleep 1  # Waits 1 second
	done
	printf "\n\n\n\n\n generation number: $run \n\n\n\n"
	rm "children.csv"
	touch "children.csv"
	javac -cp . "src/neld9968/LITCHROMOSOME.java" "src/neld9968/LITGENERATOR.java" "src/neld9968/LITSELECTOR.java"
	java -cp "src/" neld9968.LITSELECTOR

	rm "LITNUMBER.txt"
	cp "LITCSV.csv" "LITCSV$run.csv"	
	rm "LITCSV.csv"
	touch "LITCSV.csv"
	touch "LITNUMBER.txt"
done

#litnumber.txt not generated

#/Users/Luis/Documents/workspace/LITBOIZ/